[pytest]
pythonpath = .
asyncio_mode = auto
markers = 
    unit_generate_hash: marca testes unitários de gerador de hash
    unit_verify_password: marca teste unitários de verficar senha
    integration: marca testes de integração
    integration_duplicate_email: marca teste de integração com levantamento de exceção de e-mail duplicado