services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: fastapi_dev

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db
    networks:
      - default

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq_dev
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  db:
    image: postgres:17-alpine
    container_name: api_database
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - default

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  worker:
    build:
      context: ..
      dockerfile: ./common/Dockerfile
    container_name: celery_worker
    command: celery -A common.celery_app worker --loglevel=INFO
    volumes:
      - ../..:/workspaces:cached
    networks:
      - default
    env_file:
      - "../.env"
    depends_on:
      - rabbitmq
      - worker_backend

  worker_backend:
    image: postgres:17-alpine
    volumes:
      - worker-data:/var/lib/postgresql/data
    container_name: celery_backend
    env_file:
      - "../.worker_backend.env"
    ports:
      - "5000:5432"
    networks:
      - default
    

  flower:
    image: mher/flower:2.0
    container_name: flower
    env_file:
      - "../.env"
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq

volumes:
  postgres-data:
  worker-data:

networks:
  default:
    driver: bridge
